version: "3.7"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=adoptanimal
      - MONGO_INITDB_ROOT_USERNAME=voda
      - MONGO_INITDB_ROOT_PASSWORD=voda
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    networks:
      - mongodb_network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    command: bash -c "sleep 1 && node app.js -a"  
    ports:
      - "8081:8081"
    restart: always
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=voda
      - ME_CONFIG_BASICAUTH_PASSWORD=voda
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=voda
      - ME_CONFIG_MONGODB_ADMINPASSWORD=voda
    networks:
      - mongodb_network
    depends_on:
      - mongodb
    volumes: 
      - mongodb_data_container:/data/db
    links:
      - mongodb

networks: 
    mongodb_network:
      driver: bridge

volumes:
  mongodb_data_container:
      driver: local